name: build docs
on: [workflow_dispatch]
jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          path: docs

      - name: build Documentation
        run: |
          cd docs
          yarn 
          yarn build
