name: build docs
on: [workflow_dispatch]
jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          path: docs

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: docs/.vitepress/dist

      - name: build Documentation
        run: |
          cd docs
          yarn 
          yarn build
