name: build docs
on: [workflow_dispatch]
jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - name: ⚙️ Set BRAND_NAME environment variable from repo name
        run: |
          echo ${{ github.event.repository.name }}

      - name: checkout repository
        uses: actions/checkout@v3
        with:
          path: docs
