name: Build vue
on: [workflow_dispatch]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build vue
    steps:
      - uses: actions/checkout@v3
      - id: Build-vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "DeepKumbhare85"
          reponame: "dataTableTest"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
