name: Deploy Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template
        uses: actions/checkout@v3

      - name: Install Packages
        run: yarn install

      - name: Generate Build
        run: yarn build
